### ISSUE TITLE
Support Arming/Disarming

### ISSUE THREAD

**Issue by Qinusty** [davidMbrooke/texecom-connect#15]
In the README it states "It does not currently support arm/disarming.", Is this a limitation of the texecom connect protocol or a limitation of this project?

**Comment by anthonyangel** [comment]
It's supported by the Texecom protocol, just hasn't been written into this project

**Comment by Qinusty** [comment]
Following up on this before it is closed out. @mpredfearn mentioned that arming is supported and part arming is supported in his fork https://github.com/mpredfearn/texecom-connect/.

I've been playing around with this for a bit and have had some problems getting this configured with home assistant. I see the `homeassistant/alarm_control_panel/NAME/config` is available as a topic but can't see this magically picked up by home assistant during auto-discovery. Meanwhile, all other sensors are picked up perfectly by auto discovery. 

In my setup I am currently missing the support for armed/disarmed state, and the arm/part arm/disarm actions.

Is it necessary to manually configure this with https://www.home-assistant.io/integrations/manual_mqtt/?

**Comment by mpredfearn** [comment]
Hi @Qinusty,
Interesting that your auto-discovery did not work....
With my panel, it did auto-discover into home assistant (albeit quite a few versions ago?), with the following autodiscovery information:

```
'house' (alarm_control_panel.house)
MQTT discovery data:
Topic: homeassistant/alarm_control_panel/house/config
Payload
name: house
state_topic: homeassistant/alarm_control_panel/house/state
command_topic: homeassistant/alarm_control_panel/house/command
unique_id: Elite.area.house
device:
  name: Texecom Elite 64
  identifiers: '123456789'
  manufacturer: Texecom
  model: Elite 64
platform: mqtt
```
I did not have to manually configure anything in the home assistant configuration, the devices all showed up as below in home assistant -> configuration -> devices -> Texecom Elite 64

![Screenshot_2021-01-12_13-52-49](https://user-images.githubusercontent.com/12936891/104323090-abb1e480-54dd-11eb-9528-880a3172f7e2.png)

Can you turn on log_mqtt_traffic and post the config message?
